### ISSUE TITLE
List of todo items.

### ISSUE THREAD

**Issue by techsinarif** [infozapp-solutions/www-infozapp-solutions#1]
**Below is the list of to-do items.**

- [x] Create a responsive react application based on the selected HTML template.
- [ ] Replace the template content with real-world content.
- [ ] Integrate support chat-bot feature, with the website.
- [x] Make use of material ui components - [Overview - Material UI](https://mui.com/material-ui/getting-started/overview/)
- [ ] Set up cloud infrastructure.
- [ ] Create nodejs server files
